### ISSUE TITLE
Plot is empty if any point is <= 0 and y_log is used

### ISSUE THREAD

**Issue by ahardjasa** [twitter/AnomalyDetection#9] opened 2015-01-07 22:02 UTC
![blank_anomalylog](https://cloud.githubusercontent.com/assets/4095871/5654195/d1797778-9675-11e4-9bdc-680e9d0cd8a5.png)
To reproduce:
```R
data(raw_data)
raw_data[4000, "count"] <- 0
AnomalyDetectionTs(raw_data, y_log = F, plot = T)
AnomalyDetectionTs(raw_data, y_log = T, plot = T)
```
This seems to be a problem with coord_trans, as transforming the data to be plotted (after anomaly detection) and skipping add_formatted_y (it can't handle the presence of Na/NaN/Inf) will show all points with the undefined value set to 0.
![anomalylog](https://cloud.githubusercontent.com/assets/4095871/5654047/93564e86-9674-11e4-9c01-30aabd1976fe.png)

Alternatively, if the transformation is only for ease of visualization,
```R
AnomalyDetectionTs(raw_data, y_log = F, plot = T)$plot + scale_y_log10()
```
will transform the axis without changing the value of the data, which might be preferable. It will overwrite add_formatted_y, though.

I haven't submitted a fix since I'm not sure if this is desired behaviour or not, but I'd be happy to if it would be useful. And thank you for the awesome package!

**Comment by owenvallis** [comment] 2015-01-07 22:14
Thanks for catching that. The log transform option is just to help visualize the data when the anoms are extremely positive relative to the bulk of the data, so it looks like your solution would be a good one. 

Also, if the updated presents an issue with the labeling, then we might be able to add the formatted y back after the log transform.

**Comment by akejariwal** [comment] 2015-01-07 23:02
@ahardjasa Please submit a patch. Let's make sure that the formatting of y-ticks (ala 'K', 'M', ...) is retained in case of large values after taking the log. @owenvallis and @jhochenbaum will review.

**Comment by jhochenbaum** [comment] 2015-01-08 05:34
Just pulled and ran your patch and confirmed the y-axis seems to be scaling correctly. Going to look over the code and assuming all looks good we'll get this merged in. Thanks again!

**Closed** 2015-01-12 21:58 UTC
